version: "3.9"

services:
  db:
    image: postgres:16
    container_name: unahur_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unahur
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: unahur_api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./src/uploads:/app/src/uploads
    command: sh -c "npm run dev"

volumes:
  pgdata:
